### ISSUE TITLE
Add Observable.Window

### ISSUE THREAD

**Issue by lostfictions** [neuecc/UniRx#30] opened 2014-09-05 07:11 UTC
It doesn't seem like Observable.Window is implemented. Would it be possible to add it?

Thanks!

**Comment by mikeaustin** [comment] 2015-02-05 23:58
I'm learning Rx and coupling it with Unity is brilliant!  I would also like to see Window as in this Konami code example: https://gist.github.com/mattpodwysocki/2015422

Thanks for making UniRx!

**Comment by Xerios** [comment] 2016-05-14 08:55
I just encountered a moment where window would've been really useful for something I wanted to do.

Transforming several incoming +1 +2 +1 score additions in a short span into one +4 that changes if the score keeps increasing.

Also, thanks for the awesome library :)

**Comment by neuecc** [comment] 2016-08-02 03:06
duplicate of 105 issue.

**Closed by neuecc** 2016-08-02 03:06 UTC
